---
title: "X-much CXN in IrE - Part 2: Converting data to rda"
author: "Anonymous"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  word_document
bibliography: bibliography.bib
link-citations: yes
---

# Intro{-}

This document loads the pos tagged GloWbe data and then saves it as rda.

## Prep{-}

```{r}
library(tidyverse)
```


## Define directory{-}

```{r}
cpath <- "D:\\Uni\\Korpora\\Edited\\GloWbe_postagged"
```

## create file vector{-}

```{r}
cfiles <- list.files(path = cpath, pattern = ".txt", all.files = T, full.names = T, recursive = T, ignore.case = T, include.dirs = T)
#cfiles <- cfiles[1:2]
#cfiles
```


```{r}
sapply(cfiles, function(x){
  nm <- stringr::str_replace_all(x, ".*/(.*?).txt", "\\1")
  x <- scan(x, 
            what = "char", 
            sep = "", 
            quote = "", 
            quiet = T, 
            skipNul = T)
  x <- paste0(x, sep = " ", collapse = " ")
  x <- stringr::str_squish(x)
  base::saveRDS(x, file = here::here("data/GloWbe_pos", paste0(nm, ".rda")))
})
```


## Outro{-}

```{r}
sessionInfo()
```


***

The END

***

